packaging_format = 2

id = "calckey"
name = "Calckey"
description.en = "Fork of Misskey with better UI/UX, security, features"
description.fr = "Un fork de Misskey avec une meilleure interface utilisateur, la sécurité, les fonctionnalités"

version = "14.0.0rc~ynh1"

maintainers = ["oufmilo"]

[upstream]
license = "AGPL-3.0"
website = "https://i.calckey.cloud/"
demo = "https://i.calckey.cloud/"
code = "https://codeberg.org/calckey/calckey"

[integration]
yunohost = ">= 11.1.14"
architectures = "all" 
multi_instance = false
ldap = "not_relevant" 
sso = "not_relevant" 
disk = "50M" 
ram.build = "2G"
ram.runtime = "2G"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    help.en = "If enabled, Calckey will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Calckey sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]

    [resources.sources.main]
    url = "https://codeberg.org/calckey/calckey/archive/v14.0.0-rc.tar.gz"
    sha256 = "3dc6023c4c816ab3504a8f2c7d2c2b2c908cb58c0cda0821631a314a29d3b0f6"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 3020

    [resources.apt]
    packages = "ffmpeg, postgresql, build-essential, curl"

    [resources.database]
    type = "postgresql"
